import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { Shield, ShieldCheck } from 'lucide-react';
// @ts-ignore
import ReactMarkdown from 'react-markdown';

// Simulating the EULA Markdown content for now to avoid dynamic imports or fetching
const EULA_CONTENT = `
**END-USER LICENSE AGREEMENT (EULA)**

**IMPORTANT – READ CAREFULLY:** This End-User License Agreement ("EULA") is a legal agreement between You (either an individual or a single entity, hereinafter "Licensee" or "You") and AGV VENTURES (hereinafter "Licensor", "Company", or "AGV VENTURES") for the Brasa Meat Intelligence Software Product ("Software" or "System").

By clicking "I Agree", logging into the system, or otherwise using the Software, You agree to be bound by the terms of this EULA. If You do not agree to the terms of this EULA, do not install or use the Software.

---

### **1. GRANT OF LICENSE**
AGV VENTURES grants You a revocable, non-exclusive, non-transferable, limited license to access and use the Software solely for the internal operational management of the restaurant unit(s) authorized by the Licensee's employer or affiliated corporate entity, strictly in accordance with the terms of this Agreement.

### **2. SYSTEM MONITORING AND AUDIT LOGGING**
You expressly acknowledge and agree that:
a) The Software is designed to track, measure, and record operational efficiency, inventory variance, and financial impact in real-time.
b) Every interaction, data entry, modification, or omission within the System is permanently recorded in an immutable audit log linked to Your secure user credential.
c) **"The Garcia Rule":** The System enforces mandatory operational compliance. Failure to input required data, specifically regarding high-value inventory items (e.g., Picanha, Lamb), will result in an automated restriction of System access (dashboard lockout) for Your user account and/or Your store location until compliance is met.

### **3. PERFORMANCE DATA AND EMPLOYMENT CONSEQUENCES**
You understand that the operational and financial metrics generated by Your use of the Software:
a) Will be accessible to Senior Management, Area Directors, and Corporate Officers of Your organization.
b) May be used by Your employer as a quantitative basis for evaluating Your job performance.
c) **AGV VENTURES bears zero liability** for any employment-related decisions—including, but not limited to, termination, demotion, loss of bonus, or disciplinary action—taken by Your employer as a result of the data, metrics, rankings, or compliance logs generated by this Software.

### **4. CONFIDENTIALITY AND TRADE SECRETS**
The algorithms, mathematical models (including the LBS/Guest and Smart Prep projection models), database schemas, UI workflows, and underlying source code of the Software constitute highly confidential trade secrets of AGV VENTURES.
You agree NOT to:
a) Copy, screenshot, record, or transmit the System's interface or features to any third party outside Your organization.
b) Attempt to reverse-engineer, decompile, or bypass any security or logic mechanisms of the Software.
c) Share Your login credentials with any other person.

### **5. INTELLECTUAL PROPERTY RIGHTS**
All title, ownership rights, and intellectual property rights in and to the Software and any copies thereof are owned by AGV VENTURES and Alexandre Garcia. All rights not expressly granted to You are reserved by the Licensor.

### **6. TERMINATION**
This license is effective until terminated. Your rights under this EULA will terminate automatically without notice from AGV VENTURES if You fail to comply with any term(s) of this EULA. Upon termination of the license, You shall cease all use of the Software. AGV VENTURES reserves the right to digitally revoke Your access at any time.

---
*By accepting this agreement, You certify that You have read and understood its contents, and accept complete responsibility for the accuracy of the data You enter into the Brasa Meat Intelligence system.*
`;

export const EulaAgreement = () => {
    const { user } = useAuth();
    const [isAccepting, setIsAccepting] = useState(false);
    const [scrolledToBottom, setScrolledToBottom] = useState(false);

    const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
        const bottom = e.currentTarget.scrollHeight - e.currentTarget.scrollTop <= e.currentTarget.clientHeight + 50;
        if (bottom) {
            setScrolledToBottom(true);
        }
    };

    const handleAccept = async () => {
        if (!user || !user.token) return;
        setIsAccepting(true);

        try {
            const res = await fetch('/api/v1/users/accept-eula', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${user.token}`
                }
            });

            if (res.ok) {
                // Force a full logout so the user re-authenticates.
                // This ensures the backend issues a brand new JWT token with the eula_accepted: true claim,
                // preventing the frontend and backend from falling out of sync.
                alert("Agreement recorded successfully. Please log in again to continue.");
                localStorage.removeItem('brasameat_user');
                localStorage.removeItem('brasameat_selected_company');
                window.location.href = '/login';
            } else {
                alert("Failed to record acceptance. Please try again.");
                setIsAccepting(false);
            }
        } catch (error) {
            console.error("EULA API Error:", error);
            alert("Network error. Could not connect to the server.");
            setIsAccepting(false);
        }
    };

    return (
        <div className="min-h-screen bg-black flex flex-col items-center justify-center p-4">
            <div className="max-w-3xl w-full bg-[#121212] border border-brand-gold/30 rounded-lg shadow-2xl flex flex-col h-[85vh] overflow-hidden relative">

                {/* Header */}
                <div className="p-6 border-b border-[#333] shrink-0 bg-[#1a1a1a]">
                    <div className="flex items-center justify-center gap-3 mb-2">
                        <Shield className="w-8 h-8 text-brand-gold" />
                        <h1 className="text-2xl font-black text-white tracking-widest uppercase">End-User License Agreement</h1>
                    </div>
                    <p className="text-gray-400 text-center text-sm font-mono">
                        You must read and accept these terms to access Brasa Meat Intelligence.
                    </p>
                </div>

                {/* Markdown Content Area */}
                <div
                    className="flex-1 overflow-y-auto p-6 lg:p-10 prose prose-invert prose-brand max-w-none text-sm leading-relaxed text-gray-300"
                    onScroll={handleScroll}
                >
                    <ReactMarkdown>{EULA_CONTENT}</ReactMarkdown>
                </div>

                {/* Footer Gradient & Actions */}
                <div className="shrink-0 border-t border-[#333] bg-gradient-to-t from-[#0a0a0a] to-[#121212] p-6 relative">

                    {!scrolledToBottom && (
                        <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-full w-full h-12 bg-gradient-to-t from-[#121212] to-transparent pointer-events-none" />
                    )}

                    <div className="flex flex-col items-center gap-4">
                        <p className="text-xs text-gray-500 font-mono text-center max-w-xl">
                            By clicking agree, your digital signature, along with a timestamp and IP footprint, will be permanently recorded in the system audit logs.
                        </p>

                        <button
                            onClick={handleAccept}
                            disabled={!scrolledToBottom || isAccepting}
                            className={`px-8 py-4 rounded font-bold uppercase tracking-widest transition-all flex items-center justify-center gap-2 w-full max-w-sm ${scrolledToBottom && !isAccepting
                                ? 'bg-brand-gold hover:bg-yellow-500 text-black shadow-[0_0_20px_rgba(197,160,89,0.3)] active:scale-95'
                                : 'bg-[#333] text-gray-500 cursor-not-allowed border border-[#444]'
                                }`}
                        >
                            {isAccepting ? (
                                <div className="w-5 h-5 border-2 border-black border-t-transparent rounded-full animate-spin" />
                            ) : (
                                <>
                                    {scrolledToBottom ? <ShieldCheck className="w-5 h-5" /> : <Shield className="w-5 h-5" />}
                                    {scrolledToBottom ? 'I Agree to the EULA' : 'Scroll to read EULA'}
                                </>
                            )}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};
