const puppeteer = require('puppeteer');
const path = require('path');
const fs = require('fs');

const observations = [
    {
        num: "10",
        title: "THE BIGGEST LOSSES ARE OFTEN BEHAVIOR LOSSES",
        body: [
            "Inventory does not create variance.",
            "People do.",
            "Habits dictate the numbers.",
            "Control behavior, secure EBITDA."
        ],
        bottomStatement: "THE BIGGEST LOSSES ARE OFTEN BEHAVIOR LOSSES.",
        closingStatement: "Inventory does not create variance. People do.",
        hashtags: [
            "#RestaurantOperations",
            "#OperationalExcellence",
            "#HospitalityLeadership",
            "#EBITDA",
            "#BRASA"
        ],
        postCopy: "OBSERVATION #10\n\nMost restaurant losses are behavior losses, not inventory losses.\n\nIn multi-unit operations, inventory systems are designed to track the physical movement of raw assets. However, variance is not generated by the raw beef or seafood in the cooler—it is generated by the habits, shortcuts, and choices of the staff handling them.\n\nWhen an operator skips the scale at the receiving dock, or when a chef bypasses standardized yield logs because it is convenient during a rush, a financial drift is established. These behavioral deviations are small in isolation, but when scaled across dozens of units and thousands of shifts, they compound into material EBITDA decay.\n\nEBITDA is protected when we focus on stabilizing human habits rather than auditing spreadsheets."
    },
    {
        num: "11",
        title: "DELAYED VISIBILITY MULTIPLIES LOSS",
        body: [
            "Yesterday's data cannot protect today's margin.",
            "Variance compounds with every day of delay.",
            "Retrospective audits document losses instead of stopping them.",
            "Real-time telemetry is your primary EBITDA shield."
        ],
        bottomStatement: "DELAYED VISIBILITY MULTIPLIES LOSS.",
        closingStatement: "What leadership finds today started weeks ago.",
        hashtags: [
            "#EBITDA",
            "#HospitalityLeadership",
            "#SupplyChain",
            "#OperationalExcellence",
            "#BRASA"
        ],
        postCopy: "OBSERVATION #11\n\nThe true cost of operational variance is not the drift itself—it is the time it takes to detect it.\n\nWhen high-volume units experience a food cost spike, the leak is rarely a single catastrophic event. Instead, it is a silent, daily accumulation of unverified catch-weights, out-of-spec yields, and undocumented waste.\n\nIf your visibility is dependent on month-end physical counts and accounting reconciliations, you are managing in the rearview mirror. By the time leadership identifies a 3% protein cost anomaly, weeks of margin have already evaporated. You cannot retrospectively audit or recover value from food that has already been consumed.\n\nProtecting margins requires real-time telemetry, not historical autopsies."
    },
    {
        num: "12",
        title: "METRICS DO NOT CREATE ACTION",
        body: [
            "Numbers explain what happened.",
            "Accountability determines what happens next.",
            "What nobody owns rarely improves.",
            "Shift-level responsibility drives performance."
        ],
        bottomStatement: "METRICS DO NOT CREATE ACTION.",
        closingStatement: "Data informs. Ownership transforms.",
        hashtags: [
            "#Leadership",
            "#Accountability",
            "#RestaurantOperations",
            "#HospitalityLeadership",
            "#BRASA"
        ],
        postCopy: "OBSERVATION #12\n\nDashboards track metrics, but only human ownership corrects operational drift.\n\nMany restaurant groups invest heavily in data visualization and automated inventory software. Yet, simply compiling cost percentages, scrap rates, and supplier discrepancies does not secure a single dollar of gross margin if those numbers lack a designated operational owner.\n\nWithout accountability at the point of execution—at the receiving scale or the butcher block—data becomes passive noise. A dashboard can highlight a variance, but until a specific regional manager or head chef is personally responsible for correcting it on the shift, the margin leak will persist.\n\nWe do not lack data. We lack ownership."
    }
];

function getHtmlTemplate(num, title, bodyPoints, bottomStatement, closingStatement) {
    const bulletPointsHtml = bodyPoints.map(point => `      <div class="bullet-point">${point}</div>`).join('\n');
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>BRASA FIELD OBSERVATION #0${num}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    body {
      width: 1080px;
      height: 1350px; /* Portrait height */
      background-color: #000000;
      color: #ffffff;
      padding: 100px 85px;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      position: relative;
      overflow: hidden;
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    }

    /* Header styling */
    .header-block {
      font-size: 24px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 1.5px;
      color: #ffffff;
      margin-bottom: 25px;
    }

    /* Title styling */
    .title-block {
      font-family: 'Cormorant Garamond', Georgia, serif;
      font-size: 50px;
      font-weight: 700;
      letter-spacing: 0.5px;
      text-transform: uppercase;
      line-height: 1.15;
      margin-bottom: 25px;
      color: #ffffff;
    }

    /* Divider line */
    .gold-divider {
      width: 100%;
      height: 2px;
      background-color: #C8A44D;
      margin-bottom: 60px;
    }

    /* Body section */
    .body-section {
      display: flex;
      flex-direction: column;
      gap: 45px;
      flex-grow: 1;
      margin-bottom: 45px;
    }
    .bullet-point {
      font-size: 28px;
      line-height: 1.45;
      color: #ffffff;
      padding-left: 20px;
      position: relative;
      font-weight: 400;
    }
    .bullet-point::before {
      content: "•";
      position: absolute;
      left: 0;
      color: #ffffff;
    }

    /* Insight Box */
    .insight-box {
      border: 3px solid #C8A44D;
      background-color: transparent;
      padding: 30px 40px;
      text-align: center;
      margin-bottom: 60px;
    }
    .insight-text {
      font-size: 30px;
      font-weight: 700;
      letter-spacing: 1px;
      line-height: 1.35;
      text-transform: uppercase;
      color: #ffffff;
    }

    /* Closing Statement */
    .closing-statement {
      font-size: 29px;
      font-weight: 500;
      text-align: center;
      line-height: 1.4;
      color: #ffffff;
      margin-bottom: 65px;
    }

    /* Footer styling */
    .footer-divider {
      width: 100%;
      height: 1.5px;
      background-color: #C8A44D;
      margin-bottom: 20px;
    }
    .footer-block {
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 22px;
      color: #ffffff;
      font-weight: 400;
      letter-spacing: 0.5px;
    }
  </style>
</head>
<body>

  <div>
    <div class="header-block">BRASA FIELD OBSERVATION #0${num}</div>
    <div class="title-block">${title}</div>
    <div class="gold-divider"></div>
    
    <div class="body-section">
\n${bulletPointsHtml}
    </div>
  </div>

  <div>
    <div class="insight-box">
      <div class="insight-text">
        ${bottomStatement}
      </div>
    </div>

    <div class="closing-statement">
      ${closingStatement}
    </div>

    <div class="footer-divider"></div>
    <div class="footer-block">
      <div>Alexandre Garcia | Multi-Unit Restaurant Operations</div>
      <div>BRASA Meat Intelligence™ Framework</div>
    </div>
  </div>

</body>
</html>`;
}

async function main() {
    console.log('Initializing Puppeteer for Portrait format card renders...');
    let browser;
    try {
        browser = await puppeteer.launch({
            headless: true,
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu'
            ]
        });

        const page = await browser.newPage();
        
        // Define directory paths
        const baseDir = path.join(__dirname, '../../linkedin');
        const postsDir = path.join(baseDir, 'posts');
        const cardsDir = path.join(baseDir, 'cards');
        const scheduleDir = path.join(baseDir, 'schedule');

        // Create directories if they do not exist
        [postsDir, cardsDir, scheduleDir].forEach(dir => {
            if (!fs.existsSync(dir)) {
                fs.mkdirSync(dir, { recursive: true });
            }
        });

        // 1. Process Observations
        for (const obs of observations) {
            console.log(`Processing Observation #${obs.num}: ${obs.title}...`);

            // Generate HTML Content
            const htmlContent = getHtmlTemplate(
                obs.num, 
                obs.title, 
                obs.body, 
                obs.bottomStatement, 
                obs.closingStatement
            );

            // Render PNG card (1080 x 1350)
            await page.setContent(htmlContent);
            await new Promise(resolve => setTimeout(resolve, 1500)); // wait for web fonts
            await page.setViewport({
                width: 1080,
                height: 1350,
                deviceScaleFactor: 2 // High Resolution: 2160 x 2700 output
            });

            const pngPath = path.join(cardsDir, `observation_${obs.num}.png`);
            await page.screenshot({
                path: pngPath,
                type: 'png'
            });
            console.log(`- Card rendered: ${pngPath}`);

            // Generate Post Markdown
            const mdContent = `# BRASA FIELD OBSERVATION #0${obs.num}\n\n` +
                `### Post Copy\n` +
                `\`\`\`text\n` +
                `${obs.postCopy}\n\n` +
                `${obs.hashtags.join(' ')}\n` +
                `\`\`\`\n\n` +
                `### Card Info\n` +
                `*   **Headline:** ${obs.title}\n` +
                `*   **Supporting Statement:** ${obs.closingStatement}\n`;

            const mdPath = path.join(postsDir, `observation_${obs.num}.md`);
            fs.writeFileSync(mdPath, mdContent, 'utf8');
            console.log(`- Post markdown saved: ${mdPath}`);
        }

        // 2. Generate publication schedule (week_04_schedule.md)
        console.log('Generating week_04_schedule.md...');
        const scheduleContent = `# BRASA Observation Series — Week 04 Publication Schedule\n\n` +
            `This schedule contains the publication timeline, post copy, and image assets for the BRASA Field Observation series, Week 04.\n\n` +
            `| Post | Date | Time | Card Filename | Theme |\n` +
            `| :--- | :--- | :--- | :--- | :--- |\n` +
            `| **Observation #10** | 2026-06-29 | 08:30 AM EST | [observation_10.png](../cards/observation_10.png) | Behavior Leakage |\n` +
            `| **Observation #11** | 2026-07-01 | 08:30 AM EST | [observation_11.png](../cards/observation_11.png) | Delayed Visibility |\n` +
            `| **Observation #12** | 2026-07-03 | 08:30 AM EST | [observation_12.png](../cards/observation_12.png) | Metrics vs Accountability |\n\n` +
            `---\n\n` +
            `## Observation #10\n` +
            `*   **Publication Date:** June 29, 2026 (Monday)\n` +
            `*   **Publication Time:** 08:30 AM EST\n` +
            `*   **Card Asset:** [observation_10.png](../cards/observation_10.png)\n` +
            `*   **Post Copy:**\n` +
            `\`\`\`text\n` +
            `${observations[0].postCopy}\n\n` +
            `${observations[0].hashtags.join(' ')}\n` +
            `\`\`\`\n\n` +
            `---\n\n` +
            `## Observation #11\n` +
            `*   **Publication Date:** July 1, 2026 (Wednesday)\n` +
            `*   **Publication Time:** 08:30 AM EST\n` +
            `*   **Card Asset:** [observation_11.png](../cards/observation_11.png)\n` +
            `*   **Post Copy:**\n` +
            `\`\`\`text\n` +
            `${observations[1].postCopy}\n\n` +
            `${observations[1].hashtags.join(' ')}\n` +
            `\`\`\`\n\n` +
            `---\n\n` +
            `## Observation #12\n` +
            `*   **Publication Date:** July 3, 2026 (Friday)\n` +
            `*   **Publication Time:** 08:30 AM EST\n` +
            `*   **Card Asset:** [observation_12.png](../cards/observation_12.png)\n` +
            `*   **Post Copy:**\n` +
            `\`\`\`text\n` +
            `${observations[2].postCopy}\n\n` +
            `${observations[2].hashtags.join(' ')}\n` +
            `\`\`\`\n`;

        const schedulePath = path.join(scheduleDir, 'week_04_schedule.md');
        fs.writeFileSync(schedulePath, scheduleContent, 'utf8');
        console.log(`- Schedule saved: ${schedulePath}`);

        // 3. Update master content index (CONTENT_INDEX.md)
        console.log('Writing/updating CONTENT_INDEX.md...');
        let indexContent = '';
        const indexPath = path.join(baseDir, 'CONTENT_INDEX.md');
        
        if (fs.existsSync(indexPath)) {
            indexContent = fs.readFileSync(indexPath, 'utf8');
        } else {
            indexContent = `# BRASA Field Observations — Master Content Index\n\n` +
                `This index contains a list of all compiled LinkedIn posts and visual cards for the BRASA Field Observation series.\n\n` +
                `| Observation | Theme | Card Asset | Post Copy |\n` +
                `| :--- | :--- | :--- | :--- |\n`;
        }

        // Check if entries already exist, if not, append them
        if (!indexContent.includes('Observation #10')) {
            indexContent += `| **Observation #10** | Behavior Leakage | [observation_10.png](./cards/observation_10.png) | [observation_10.md](./posts/observation_10.md) |\n`;
        }
        if (!indexContent.includes('Observation #11')) {
            indexContent += `| **Observation #11** | Delayed Visibility | [observation_11.png](./cards/observation_11.png) | [observation_11.md](./posts/observation_11.md) |\n`;
        }
        if (!indexContent.includes('Observation #12')) {
            indexContent += `| **Observation #12** | Metrics vs Accountability | [observation_12.png](./cards/observation_12.png) | [observation_12.md](./posts/observation_12.md) |\n`;
        }

        fs.writeFileSync(indexPath, indexContent, 'utf8');
        console.log(`- Master index updated: ${indexPath}`);
        
        console.log('SUCCESS: All portrait observations, schedule, and content index have been generated successfully!');
    } catch (err) {
        console.error('CRITICAL ERROR in rendering loop:', err);
    } finally {
        if (browser) {
            await browser.close();
        }
    }
}

main();
