import { PrismaClient } from '@prisma/client';
import { startOfMonth, endOfMonth, differenceInDays } from 'date-fns';

const prisma = new PrismaClient();

export class DataIntegrityWatchdog {

    /**
     * Executes the Enterprise Fail-Closed check.
     * Evaluates Unaccounted Loss and Missing Scans.
     */
    static async performIntegrityAudit(storeId: number, start: Date, end: Date) {
        
        let isCompromised = false;
        let lockReason = '';

        // 1. Check for Critical UNACCOUNTED_LOSS generated by the State Engine
        const lossEvents = await prisma.boxLifecycleEvent.findMany({
            where: {
                store_id: storeId,
                timestamp: { gte: start, lte: end },
                event_type: 'ADMIN_ADJUST',
                reason: { contains: 'UNACCOUNTED_LOSS' }
            }
        });

        const totalLostLbs = lossEvents.reduce((acc, ev) => acc + (ev.weight_variance || 0), 0);

        if (totalLostLbs > 0) {
            isCompromised = true;
            lockReason += `CRITICAL: UNACCOUNTED LOSS DETECTED. ${totalLostLbs.toFixed(2)} lbs of protein vanished without a logged WASTE event. `;
        }


        // 2. Check for GHOST MEAT (Received but NEVER Prepped, AND NOT IN COOLER)
        // We look for boxes that are mathematically 'missing'.
        // If a box is RECEIVED but inventory was done and the box was not counted -> GHOST MEAT.
        // For now, tracking Unaccounted_Loss from consumption serves as our primary block constraint.
        
        // 3. Check for GARCIA RULE BLOCK (No Waste Log)
        const recentWasteLogs = await prisma.wasteLog.findMany({
            where: {
                store_id: storeId,
                date: { gte: new Date(Date.now() - 48 * 60 * 60 * 1000) } // Last 48 hours
            }
        });
        
        if (recentWasteLogs.length === 0) {
            // Technically a Garcia Rule violation. We won't block the dashboard completely for this, 
            // but we could. For Enterprise Hardlock, let's flag an alert on the dashboard.
            // Dashboard should still load to show the warning, but scores will be withheld.
        }

        return {
            isCompromised,
            lockReason,
            totalLostLbs
        };
    }

}
